map_x: 10
map_y: 10
stats_x: 50
wall_lists:
- - - 3
  - - 3
    - 8
    - 9
  - - 1
    - 2
    - 3
    - 5
    - 8
    - 9
  - - 5
  - - 0
    - 1
    - 2
    - 3
    - 5
    - 6
    - 7
    - 8
  - - 1
    - 3
  - - 1
    - 3
    - 5
    - 6
    - 8
  - - 5
    - 6
    - 8
  - - 1
    - 2
    - 3
    - 8
  - - 3
    - 5
    - 6
- - - 3
    - 4
    - 5
  - - 3
    - 5
    - 8
    - 9
  - - 1
    - 2
    - 3
    - 5
  - - 5
  - - 5
    - 6
    - 7
    - 8
  - - 1
    - 3
  - - 1
    - 2
    - 3
    - 5
    - 6
    - 8
  - - 5
    - 6
    - 8
  - - 3
  - - 0
    - 9
